### ISSUE TITLE
New Dethorn version

### ISSUE THREAD

**Issue by BC46** [IrateRedKite/freelancer-dethorned#1]
A new version of the Dethorn tool has been released. This update fixes a bug that essentially caused converted files to not always be exact 1-1 translations (missing entries). Therefore, you might want to consider re-converting all the files in this project with the new Dethorn version.

**Comment by IrateRedKite** [comment]
@BC46 Are you certain adoxa's new dethorn is without issues? I've run it on the directory, and a quick check over the cutscene files shows changes like this:

```
-entity_name = "ambi_LtG00_Deck_Ylw_East_Pnt",
+entity_name = "ambi_LtG00_Deck_Ylw_03oc_Pnt",
```
```
-animation = "Sc_MLHEAD_MOTION_SHAKHEAD_YES_TRENT_000LV_XA_%",
+animation = "Sc_MLHEAD_MOTION_SHAKHEAD_YES_000LV_XA_%",
```

I'm not confident that some of the replacement animations here are actually valid, as I know Trent has specific data associated with his skeleton! Have you run into anything like this with cutscene fixes for HD edition? The examples here can be found specifically in [SCRIPTS/STORY/s075x_nrml_orillion_li_05_deck2_01.thn](https://github.com/IrateRedKite/freelancer-dethorned/commit/7e2f4fa8b53afc99e1dbedf71baaa4a175e58426#diff-bf4ad479ad573667089fb17a78f6ee190942ee9837ce0ef5938ed6f7c9b888b8)

**Comment by IrateRedKite** [comment]
After our discussion on discord, I'm now confident that these diffs are as a result of changes made by JFLP. I'll update the readme and merge the 1.01 branch accordingly!
